[tool.poetry]
name = "twitch_bot"
version = "0.1.0"
description = ""
authors = ["fritobag <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
